// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALkfUGP0tDfx6HAd2UHMOQnTiPI5o1pyY',
    appId: '1:215675111660:web:da33ee4ee871e95eb53dc9',
    messagingSenderId: '215675111660',
    projectId: 'school-app-2ce90',
    authDomain: 'school-app-2ce90.firebaseapp.com',
    storageBucket: 'school-app-2ce90.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5NAzg-crL7i1zMUIxuPTKrvHoO3K-HXI',
    appId: '1:215675111660:android:ded1f0ab7a81fbe2b53dc9',
    messagingSenderId: '215675111660',
    projectId: 'school-app-2ce90',
    storageBucket: 'school-app-2ce90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEOubuI5rj28B55gDwfk8m7VNjA0fD3pM',
    appId: '1:215675111660:ios:35c6e72533c58abcb53dc9',
    messagingSenderId: '215675111660',
    projectId: 'school-app-2ce90',
    storageBucket: 'school-app-2ce90.firebasestorage.app',
    iosBundleId: 'com.example.stupassFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEOubuI5rj28B55gDwfk8m7VNjA0fD3pM',
    appId: '1:215675111660:ios:35c6e72533c58abcb53dc9',
    messagingSenderId: '215675111660',
    projectId: 'school-app-2ce90',
    storageBucket: 'school-app-2ce90.firebasestorage.app',
    iosBundleId: 'com.example.stupassFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALkfUGP0tDfx6HAd2UHMOQnTiPI5o1pyY',
    appId: '1:215675111660:web:e70394e4c70bb751b53dc9',
    messagingSenderId: '215675111660',
    projectId: 'school-app-2ce90',
    authDomain: 'school-app-2ce90.firebaseapp.com',
    storageBucket: 'school-app-2ce90.firebasestorage.app',
  );
}
